brew 'curl'
brew 'node'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'firefox'
cask 'google-chrome'
tap 'caskroom/fonts'
cask 'font-inconsolata-for-powerline'
cask 'iterm2'
cask 'slack'
cask 'sublime-text'
